SUPABASE_URL = "https://tlvbaaqtsblnpltsxaet.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRsdmJhYXF0c2JsbnBsdHN4YWV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODk1MTkwMjUsImV4cCI6MjEwNTA5NTAyNX0.Wq6ZuDgldOKw8XfIAPe-cXJxwJ6f115Ma1MHmLRRpT8"
